export type MotherStoreType = {
  id: string;
  code: string | null;
  is_synced: number;
  is_deleted: number;
  husband_name: string | null;
  ethnicity: string | null;
  education: string | null;
  photo: string | null;
  first_name: string | null;
  last_name: string | null;
  phone_number: string | null;
  date_of_birth: string | null;
  address_locality: string | null;
  address_house_number: string | null;
  address_province: string | null;
  address_district: string | null;
  address_municipality: string | null;
  address_ward: string | null;
  income: string | null;
  occupation: string | null;
  blood_group: string | null;
  jati_code: string | null;
  lmp_date: string | null;
  parity: number | null;
  gravida: number | null;
  cover_photo: string | null;
  emergency_contact_number: string | null;
  alias: string | null;
  partner_name: string | null;
  partner_mobile: string | null;
  partner_age: string | null;
  created_at: string;
  updated_at: string;
};

export type CreateMotherPayload = {
  id: string;
  code?: string;
  husband_name?: string;
  ethnicity?: string;
  education?: string;
  photo?: string;
  first_name?: string;
  last_name?: string;
  phone_number?: string;
  date_of_birth?: string;
  address_locality?: string;
  address_house_number?: string;
  address_province?: string;
  address_district?: string;
  address_municipality?: string;
  address_ward?: string;
  income?: string;
  occupation?: string;
  blood_group?: string;
  jati_code?: string;
  lmp_date?: string;
  parity?: number;
  gravida?: number;
  cover_photo?: string;
  emergency_contact_number?: string;
  alias?: string;
  partner_name?: string;
  partner_mobile?: string;
  partner_age?: string;
  is_synced?: boolean;
};
